### ISSUE TITLE
Installation problems 

### ISSUE THREAD

**Issue by jbmsamba** [AndyPL22/ForestTools#1]
I have been trying to install ForesTools but the process has been failing apparently due to the failure of installing some of its dependencies. Below the error message:
.
.
.
* installing *source* package ‘rgeos’ ...
** package ‘rgeos’ successfully unpacked and MD5 sums checked
configure: CC: clang
configure: CXX: clang++
configure: rgeos: 0.3-23
checking for /usr/bin/svnversion... yes
configure: svn revision: 546
checking for geos-config... no
no
configure: error: geos-config not found or not executable.
ERROR: configuration failed for package ‘rgeos’
* removing ‘/usr/local/lib/R/3.3/site-library/rgeos’
Warning in install.packages :
  installation of package ‘rgeos’ had non-zero exit status
* installing *source* package ‘rgdal’ ...
** package ‘rgdal’ successfully unpacked and MD5 sums checked
configure: CC: clang
configure: CXX: clang++
configure: rgdal: 1.2-6
checking for /usr/bin/svnversion... yes
configure: svn revision: 651
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘rgdal’
* removing ‘/usr/local/lib/R/3.3/site-library/rgdal’
Warning in install.packages :
  installation of package ‘rgdal’ had non-zero exit status
ERROR: dependency ‘rgdal’ is not available for package ‘APfun’
* removing ‘/usr/local/lib/R/3.3/site-library/APfun’
Warning in install.packages :
  installation of package ‘APfun’ had non-zero exit status
ERROR: dependencies ‘rgeos’, ‘APfun’ are not available for package ‘TileManager’
* removing ‘/usr/local/lib/R/3.3/site-library/TileManager’
Warning in install.packages :
  installation of package ‘TileManager’ had non-zero exit status
ERROR: dependencies ‘rgeos’, ‘rgdal’, ‘TileManager’, ‘APfun’ are not available for package ‘ForestTools’
* removing ‘/usr/local/lib/R/3.3/site-library/ForestTools’
Warning in install.packages :
  installation of package ‘ForestTools’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/03/hn6ns80100ggs3xs47dwxmj00000gn/T/RtmpApqG9O/downloaded_packages’

**Comment by andrew-plowright** [comment]
Seems like the problems lie with the `rgeos`  and `rgdal` installation. Try installing them on their own.

```
install.packages(c("rgeos", "rgdal"))
```

If they install successfully, the other packages shouldn't have any problems. Otherwise check out this potential solution:

http://stackoverflow.com/questions/34333624/trouble-installing-rgdal

**Comment by juliannosambatti** [comment]
Hi Andy, this is a dockerfile that seemingly solves the issue. 

https://github.com/tesera/ForestTools

Best
Julianno Sambatti

**Comment by andrew-plowright** [comment]
Awesome. Thanks for that!
