### ISSUE TITLE
Statistics by polygon

### ISSUE THREAD

**Issue by Tobias1234** [AndyPL22/ForestTools#10]
I am using my own data to get statistics by polygon.
I am trying the code below to get statistics by block, but I get the error "Error in .local(x, y, returnList, fn, ...) :  identicalCRS(x, y) is not TRUE" .
Why is that?

library(ForestTools)
library(raster)
library(maptools)
library(rgdal)
library(sp)

# Load a canopy height model
inCHM <- raster("H:\\träden/klassad.tif")
# Set function for determining variable window radius
winFunction <- function(x){x * 0.40 + 0.6}

# Set minimum tree height (treetops below this height will not be detected)
minHgt <- 5

# Detect treetops in demo canopy height model
ttops <- vwf(inCHM, winFunction, minHgt)
# Plot CHM
plot(inCHM, xlab = "", ylab = "", xaxt='n', yaxt = 'n')

# Add dominant treetops to the plot
plot(ttops, col = "blue", pch = 20, cex = 0.5, add = TRUE)

# Load the 'lager.shp' file
xx <- readOGR("H:/träden", "lager")
plot(xx)

sp_summarise(ttops, areas = xx, variables = NULL, statFuns = NULL)

**Comment by andrew-plowright** [comment]
Hi Tobias, could you run these lines and tell me what they give you?
```
library(raster)
crs(xx)
crs(inCHM)
crs(ttops)
```

**Comment by Tobias1234** [comment]
Hi Andrew,
I did some adjustments in my code and added some lines in the end. The tricky part for me is to convert my shapefile to a SpatialPolygonsDataFrame. Original raster file and shapefile are in coordinate system EPSG:3008
```
library(ForestTools)
library(raster)
library(maptools)
library(rgdal)
library(sp)

# Load a canopy height model
inCHM <- raster("H:\\träden/klassad.tif")
# Set function for determining variable window radius
winFunction <- function(x){x * 0.40 + 0.6}

# Set minimum tree height (treetops below this height will not be detected)
minHgt <- 5

# Detect treetops in demo canopy height model
ttops <- vwf(inCHM, winFunction, minHgt)
# Plot CHM
plot(inCHM, xlab = "", ylab = "", xaxt='n', yaxt = 'n')

# Add dominant treetops to the plot
plot(ttops, col = "blue", pch = 20, cex = 0.5, add = TRUE)

xx <- readShapePoly(system.file("H:/träden/lager.shp", package="maptools")[1],
xx <- readShapePoly("H:/träden/lager.shp", IDvar=NULL, proj4string=CRS(as.character(NA)),
plot(xx, border="blue", axes=TRUE, las=1)
text(coordinates(xx), labels=row.names(xx), cex=0.6)
as(xx, "data.frame")
plot(xx, add = TRUE, border =  "darkmagenta", lwd = 2)
library(raster)
crs(xx)
crs(inCHM)
crs(ttops)`
```
**The lines give me**:
```
CRS arguments:
 +proj=tmerc +lat_0=0 +lon_0=13.5 +k=1 +x_0=150000 +y_0=0 +ellps=GRS80
+units=m +no_defs 
> crs(inCHM)
CRS arguments:
 +proj=tmerc +lat_0=0 +lon_0=13.5 +k=1 +x_0=150000 +y_0=0 +ellps=GRS80
+towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
> crs(ttops)
CRS arguments:
 +proj=tmerc +lat_0=0 +lon_0=13.5 +k=1 +x_0=150000 +y_0=0 +ellps=GRS80
+towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
> —
Error: unexpected input in "—"

```
**My viewer looks like this**
![Rview](https://user-images.githubusercontent.com/7010225/64407365-72b16680-d084-11e9-831d-c75d7b096358.JPG)

**Comment by andrew-plowright** [comment]
Hi Tobias,

I believe the problem here is a recurring issue with how the `sp` and `raster` packages deal with projections. If you look at the proj4 strings for your datasets, you'll see that they differ slightly:
```
+proj=tmerc +lat_0=0 +lon_0=13.5 +k=1 +x_0=150000 +y_0=0 +ellps=GRS80
+towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
```
vs
```
+proj=tmerc +lat_0=0 +lon_0=13.5 +k=1 +x_0=150000 +y_0=0 +ellps=GRS80
+units=m +no_defs 
```
In truth, these two are functionally the same, but `sp` (which is the underlying package being used by `ForestTools` to perform spatial operations) does not recognize this.

An easy solution is just to do
```
crs(xx) <- crs(inCHM)
```

This will change `xx` 's proj4 string without modifying the data, and should solve the problem. Of course, this is a bit risky since you need to be sure that `xx` is, in fact, properly projected.

Let me know if this works.

**Comment by Tobias1234** [comment]
Hi Andrew,
It works like a charm!
Best, Tobias

![träden](https://user-images.githubusercontent.com/7010225/64595494-5aa65380-d3b2-11e9-9dd7-644d06c6e3c0.png)

**Comment by andrew-plowright** [comment]
Great, glad to hear it.
