### ISSUE TITLE
VWF: w must have uneven sides

### ISSUE THREAD

**Issue by HarveyGo** [AndyPL22/ForestTools#11]
I still got the problem even if it uses celling function and check if it's uneven integer, many times. Just can't figure it out.
Maybe we should add "{ }" after "if" in line-129?

**Comment by andrew-plowright** [comment]
The brackets shouldn't affect how the code works, but I can give it a try. Could you upload a sample CHM that is causing the issue?

**Comment by HarveyGo** [comment]
Sure, thanks!
Here is my code:
lin <- function(x){x*0.25}
ttops <- vwf(CHM = wbhsCHM, winFun = lin, minHeight = 5, maxWinDiameter = 500, verbose = TRUE)
[CHM.zip](https://github.com/andrew-plowright/ForestTools/files/3972370/CHM.zip)

**Comment by andrew-plowright** [comment]
Hi Harvey, I wasn't able to reproduce the error. This issue may have already been fixed. Could you pull the latest Github version of the package and try again? 

Also, FYI: the CHM you're using is very high resolution, which will slow down the detection considerably (it took 30 minutes on my laptop). It should generally only take a few seconds. I'd recommend resampling to 0.25 m resolution, which should speed things up without noticeably affecting the results.

Let me know how it goes.

**Comment by HarveyGo** [comment]
Hi Andrew.
I just copied the code to R scripy then ran it on original data, there was no error. Then I resampled it to 0.25m resolution, no error, either. The error just happened when I used the vwf function in package with original data. 
And thanks for your advice, it has been a lot faster after resampling, appreciate it.

**Comment by andrew-plowright** [comment]
Glad that resolved the issue.
