### ISSUE TITLE
Alternative method for vectorizing crowns

### ISSUE THREAD

**Issue by ajlyons** [AndyPL22/ForestTools#12]
Thanks Andrew for creating and sharing such an awesome package! As a FYI, I found an alternative method to vectorize the tree crowns using the [terra](https://github.com/rspatial/terra) package (successor to the raster package, currently in beta), that doesn't require installing OSGeoW. Same functionality as `mcws(..., format="polygons")`, but slightly simpler setup. I think.

```
crwn_rst <- mcws(..., format = "raster")

library(terra)

## Convert crwn_rst from raster to SpatRaster (from terra package)
crwn_spatrst <- as(crwn_rst, "SpatRaster")

## Convert the raster zones to polygons (uses GDAL, fast)
crwn_spatvec <- terra::as.polygons(crwn_spatrst)

## Convert SpatVec object to sf (via export to Shapefile - klunky)
tmp_fn <- tempfile(fileext = ".shp")
terra::writeVector(crwn_spatvec, tmp_fn)
crwn_sf <- sf::st_read(tmp_fn)

## Add crown area and treetop height to the attribute table
crwn_ah_sf <- crwn_sf %>% 
  dplyr::mutate(area = st_area(crwn_sf)) %>% 
  sf::st_join(ttops_sf, join = st_intersects)
```

**Comment by andrew-plowright** [comment]
Improving the rasterization of outlines is #1 on my list of things to do for `mcws`. You may have saved me a lot of time here, Andy. Thanks!
