### ISSUE TITLE
install.packages("ForestTools") doesn't work on R version 4.03

### ISSUE THREAD

**Issue by Hannes-Ole** [AndyPL22/ForestTools#15]
Like the titel says, install.packages("ForestTools") doesn't work on **R version 4.03**. I also tried R version 4.02. Is this package no longer maintained or is this a problem of a CRAN mirror or are there workarounds?

    install.packages("ForestTools")

    Warning in install.packages :
     package ‘ForestTools’ is not available for this version of R

`R.Version()` gives me (amongst other things):

    $platform
     [1] "x86_64-w64-mingw32"
    $version.string
     [1] "R version 4.0.3 (2020-10-10)"

**Comment by andrew-plowright** [comment]
Hi there, one of ForestTools' dependencies (radiomics) was taken off of CRAN, so for the moment ForestTools itself cannot be installed using that method. I am working to fix this, though.

In the meantime, using `devtools::install_github("andrew-plowright/ForestTools")` should work

**Comment by Hannes-Ole** [comment]
cool, thanks for the quick answer.
`devtools::install_github("andrew-plowright/ForestTools")` does indeed work.
I've seen that you integrated the radiomics code in this project, hope you get it running soon. Thanks for your good work.

**Comment by andrew-plowright** [comment]
Great, glad that worked for you. It should be back up on CRAN this week
