### ISSUE TITLE
The crown shapefile has some consistent gaps  

### ISSUE THREAD

**Issue by fsecanho** [AndyPL22/ForestTools#17]
Hi Andrew,

First of all, thank you for creating this package. I'm new to it but I see a gigantic potential here. 
Just a short background on the issue: my final goal is to use a canopy height model derived from Lidar data to create a tree list of a given area with tree height, crown diameter, and hopefully DBH. However, I'm getting a funky crown area shapefile which is missing some of the crowns in some "lines" across the area (please, see the image below). I tried to run the code using a nearby area but the results were similar. My CHM has a spatial resolution of 5ft and this is the code I'm using:

```
chm <- raster("C:/Fabio_files/Projects/Temp/TreeTop/CHM5ft_area2.tif")
lin <- function(x){x * 0.05 + 0.01}
ttops <- vwf(CHM = chm, winFun = lin, minHeight = 16)
crowns <- mcws(treetops = ttops, CHM = chm, format = "polygons", minHeight = 12, verbose = FALSE)
```
These are the "lines" with the CHM on the background:
![image](https://user-images.githubusercontent.com/87711296/161149104-511a103b-39db-4f89-87d2-e7202187f009.png)

Then, with the satellite imagery on the background, making the "lines" more visible. 
![image](https://user-images.githubusercontent.com/87711296/161149186-d43a9c89-9b29-47b6-9380-ac99bfa9fb0c.png)

Finally, the CHM only, which does not appear to have such "lines". My first thought was that the CHM was defective, but apparently it looks good.
![image](https://user-images.githubusercontent.com/87711296/161149299-ced107bd-4461-4b41-be9b-b8ddc9d8abf0.png)

Any idea on what is going on here? Thank you very much!

This is the CHM that I'm using:
[CHM5ft_area2.tif.zip](https://github.com/andrew-plowright/ForestTools/files/8393080/CHM5ft_area2.tif.zip)

**Comment by andrew-plowright** [comment]
Hi there. I've traced the error to the underlying `raster::rasterToPolygons` function, which unfortunately I don't have any control over. However, the reason why it's creating these weird polygons is not entirely clear.

A few things:

When generating the segments as rasters, everything looks fine:
```
mcws(treetops = ttops, CHM = chm, format = "raster", minHeight = 12, verbose = FALSE)
```

![image](https://user-images.githubusercontent.com/13895397/161170489-b403fe0d-68da-4a07-8a02-4bb27a27a05c.png)

Furthermore, when doing the conversion to polygons using gdal (which I recommend since it's much faster), they also look fine.
```
mcws(treetops = ttops, CHM = chm, format = "polygons", OSGeoPath = "C:/OSGeo4W64", minHeight = 12, verbose = FALSE)
```

![image](https://user-images.githubusercontent.com/13895397/161170648-9186ab91-1037-4caf-a493-49924496890c.png)

So clearly the issue is with `raster::rasterToPolygons`, but I'm not sure what's causing the problem. If you have OSGeo installed on a Windows machine, I'd suggest using the second option shown above. If not, I'd recommend generating the outlines as rasters and using another library or tool to convert them to polygons.

Sorry if that isn't more helpful. If you do figure out the problem, let me know!

Andrew

**Comment by fsecanho** [comment]
Thank you very much, Andrew! That was very helpful! 

I was able to generate a raster layer, which looks good, but I'm getting an error when generating a shapefile. Do you know if I can download the "gdal_polygonize.bat" alone? Or perhaps you could share this file here?

```
Error in APfun::APpolygonize(ws.ras, OSGeoPath = OSGeoPath) : 
  Could not find required file 'C:/OSGeo4W64/bin/gdal_polygonize.bat'
```

Thanks!

**Comment by andrew-plowright** [comment]
Glad that could help. I don't think `gdal_polygonize.bat` will work on its own. It requires a bunch of libraries that are packaged with the GDAL installation. To be honest, I'm not an expert at configuring GDAL, and the way that it's accessed by `APfun` is probably not ideal. However, GDAL really is super useful when doing geoprocessing, so it's definitely worth installing if you haven't already. If you're on Windows, you should be able to install the basics using the OSGeo4W installer (you don't need QGIS and GRASS and the other stuff): https://trac.osgeo.org/osgeo4w/

Once that's installed, just be sure you're providing the right path here (I don't think that C:/OSGeo4W64 is the default anymore) :
```
mcws(treetops = ttops, CHM = chm, format = "polygons", OSGeoPath = "C:/OSGeo4W64", minHeight = 12, verbose = FALSE)
```

**Comment by fsecanho** [comment]
I had OSGeo4W installed on my Windows machine, and I reinstalled it. Nonetheless, no success. I'm still getting the same error. I found this thread that might help: https://gis.stackexchange.com/questions/192771/how-to-speed-up-raster-to-polygon-conversion-in-r
Is there any other possible solution that I'm missing here?
Thanks!

**Comment by andrew-plowright** [comment]
Oh, yes. There's nothing special about `gdal_polygonize`, there's actually several different implementations of raster-to-polygon algorithms out there. I've heard of the one in the `stars` package before but haven't tried it. In fact, the top answer in the link you sent refers to John Baumgartner's solution, which is actually the one I implemented in `APfun`. Do whatever's easiest!

**Comment by fsecanho** [comment]
Right, but can I use one of these options in the crown's function? In other words, I don't want to run the function generating the crowns' layer as a raster, but as a shapefile, so it keeps all the attributes (e.g., tree height, crown diameter, crown area, and tree ID). Is it possible? Thanks!

**Comment by andrew-plowright** [comment]
Ah, no you'd need to join those attributes after the fact. But that's actually what happens "under the hood" anyways. The segments are generated as rasters first and then converted. You can check out what happens here and just recreate it outside of the function:

https://github.com/andrew-plowright/ForestTools/blob/c2e9fb55ae08881881051301207440af6f1be300/R/mwcs.R#L132-L172

**Comment by fsecanho** [comment]
I'll play around and see if I can solve it. Thanks a lot! 
By the way, have you tried to estimate DBH using the crowns and trees' information? I'm trying to use height and crown area/diameter/radius to estimate DBH.

**Comment by andrew-plowright** [comment]
Estimating DBH is one of the most commonly sought-after applications for this type of analysis. There's quite a bit of literature on it. Most people seem to conclude that it's very hard to do consistently, and almost impossible when accounting for wide varieties of forest types, conditions and compositions. Not saying you shouldn't try, though -- good luck! :)

**Comment by fsecanho** [comment]
I'm following some leads but nothing consistent, as you mentioned. My best guess is to use a regression model for each forest type of the area, but it's still challenging. Thanks a lot!
