### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [AndyPL22/ForestTools#18]
This package and **APfun** depend on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by rsbivand** [comment]
Fails CMD check in a scenario using sp evolution status 2 (substitute use of rgdal with sf for projection/transformation/CRS) and absence of retiring packages from the library path; new blog https://r-spatial.org/r/2023/04/10/evolution3.html. Action needed soon, also for `APfun`!

**Comment by rsbivand** [comment]
See also https://r-spatial.org/r/2023/05/15/evolution4.html; take action now.

**Comment by rsbivand** [comment]
Please act now, `rgdal` and `maptools` will be gone in three months.

**Comment by rsbivand** [comment]
@andrew-plowright Please act now, rgdal and maptools will be gone in three months.

**Comment by andrew-plowright** [comment]
Resolved with version 1.0.0 of ForestTools. On CRAN now.

**Comment by rsbivand** [comment]
@andrew-plowright No, `APfun` 0.1.6 is on CRAN, and should be archived by you if no longer required, that is if `ForestTools` now no longer needs this package.

**Comment by andrew-plowright** [comment]
> @andrew-plowright No, `APfun` 0.1.6 is on CRAN, and should be archived by you if no longer required, that is if `ForestTools` now no longer needs this package.

@rsbivand  Can you advise on the procedure for archiving a CRAN package? Should I just email CRAN with a request?

**Comment by rsbivand** [comment]
Yes, I do not see other instructions in https://cran.r-project.org/web/packages/policies.html or https://cran.r-project.org/doc/manuals/r-release/R-exts.html. I think a short informative subject could help.
