### ISSUE TITLE
Canopy Analysis Tutorial in Cran.r-project not working anymore. 

### ISSUE THREAD

**Issue by ns-1m** [AndyPL22/ForestTools#24]
Hi Andrew, 

This link below is not working anymore.
https://cran.r-project.org/web/packages/ForestTools/vignettes/treetop_analysis.html

Probably good to place this tutorial in Wiki (here) in ForestTools github, so it will not be affected by changes in  cran r repository changes.

Thanks, Noli

**Comment by andrew-plowright** [comment]
Hi Noli, I actually just resubmitted the package to CRAN today so the link should be functional again shortly.

But I will also move the tutorial to the Git's wiki. Thanks for the suggestion!

https://github.com/andrew-plowright/ForestTools/issues/25

**Comment by dpessi** [comment]
Hello,

The problem was solved?
