### ISSUE TITLE
Process error with pack ForestTools: vwf function

### ISSUE THREAD

**Issue by dpessi** [AndyPL22/ForestTools#28]
Hello, 

Mr. Andrew, I'm trying to plot the ForestTools pack example, but when I try to process the line "ttops <- vwf(chm, winFun = lin, minHeight = 2)", give me a error result: "Error in `[[<-.data.frame`(`*tmp*`, IDfield, value = 1:0) : 
  replacement has 2 rows, data has 0 In addition: There were 50 or more warnings (use warnings() to see the first 50)".

What is this? I just try to process your script in: https://cran.r-project.org/web/packages/ForestTools/vignettes/treetop_analysis.html, but the process keeps giving error.

I will glad to received your answer.

Thank you.

**Comment by andrew-plowright** [comment]
Can you confirm (using `sessionInfo()` what versions of the `sf`, `terra` and `ForestTools` you have?

**Comment by dpessi** [comment]
This: 
other attached packages:
[1] sf_1.0-14         terra_1.7-3       raster_3.6-14     sp_1.6-0          installr_0.23.4   ForestTools_1.0.0

**Comment by andrew-plowright** [comment]
And can you confirm the message you get after running this exact code? Be sure to start a fresh R session first.

```
install.packages(c("terra", "sf", "ForestTools"))

library(ForestTools)
library(terra)
library(sf)

chm <- terra::rast(kootenayCHM)

lin <- function(x){x * 0.05 + 0.6}

ttops <- vwf(chm, winFun = lin, minHeight = 2)
```

**Comment by dpessi** [comment]
It's working!

The version packages:
sf_1.0-14 
terra_1.7-46
ForestTools_1.0.0

I see that the terra pack is different. 

I appreciate it. 

Dhonatan Pessi
