### ISSUE TITLE
The crown shapefile has some consistent gaps

### ISSUE THREAD

**Issue by nealresearch** [AndyPL22/ForestTools#32]
Hi, 

My problem is similar to the issue opened by fsecanho. Some of the crowns are incomplete and have a box shape, even though there are chm pixels underneath. 

![error_polygon](https://github.com/user-attachments/assets/80c6cc9d-6b27-4ec3-9b22-f7f896aa64d5)

I tried changing the format to raster and then converting to polygon, however the raster doesnot seem to have segment. it combines all the polygon into one. 

![raster](https://github.com/user-attachments/assets/188a652a-d5ed-44ed-838f-84b669cdc781)

Here is my code

library("lidR")
library("raster")
library(dplyr)
library(RANN)
library(rgdal)
library(terra)
library(sf)
library(mmand)
library(ggplot2)

# Read LAS file and set CRS

nlas <- readLAS("havel1km.laz")
las <- filter_poi(nlas, nlas$Z>3)
st_crs(las) <- 25833

chm_canopy <- rasterize_canopy(las, res = 0.5, p2r(0.9), na.fill = kriging())

crs_chm <- crs(chm_canopy)

gf_0.3 <- focalWeight(chm_canopy, 0.3, "Gauss")
chm_smooth_0.3 <- focal(chm_canopy, w = gf_0.3)

gf_0.4 <- focalWeight(chm_canopy, 0.4, "Gauss")
chm_smooth_0.4 <- focal(chm_canopy, w = gf_0.4)

chm_final <- ifel(chm_canopy <= 5, chm_smooth_0.3, chm_smooth_0.4)
chm_final[is.na(chm_final)] <- 0

chm <- raster::raster(chm_final)
extent(chm) <- c(las@header$`Min X`,las@header$`Max X`,las@header$`Min Y`, las@header$`Max Y`)
crs(chm) <- crs_chm

ttops <- read_sf("havel1km_filter.shp")
ttops_df <- st_set_geometry(ttops, NULL)
ttops_coords <- st_coordinates(ttops)[, 1:2]# assuming columns 1 and 2 are your X and Y coordinates
ttops_sp <- SpatialPointsDataFrame(ttops_coords, ttops_df)
mcws_segments_grid <- (ForestTools::mcws(treetops = ttops_sp, CHM = chm, format = "raster", minHeight = 5))

Do you have any idea on how to solve this? Thank you very much!
data: 
[havel_error_data.zip](https://github.com/user-attachments/files/16929045/havel_error_data.zip)

**Comment by andrew-plowright** [comment]
Hi @nealresearch. You closed this issue. Has it been resolved? The crowns looked as expected on my end. Do you have the latest versions of lidR and ForestTools?

![image](https://github.com/user-attachments/assets/fcc0e980-9b87-4bcd-b495-a3d813cce5ad)

**Comment by nealresearch** [comment]
Hi, there was a mistake on my part, i thought i had updated the package but it was not. After the update everything is fine. However, in the previous version the crown area was calculated automatically, has it been removed in the newer version?

**Comment by andrew-plowright** [comment]
Yes, the last big update to ForestTools dropped all direct usage of `rgeos`, `rgdal`, and `sp` in favour of `sf`. To get the crown area, just run `sf::st_area` on the output of `mcws`

**Comment by nealresearch** [comment]
Thank you very much.
