### ISSUE TITLE
Trees localisation parameters

### ISSUE THREAD

**Issue by totor2027** [AndyPL22/ForestTools#33]
Thank you for your fantastic tools. 
I want to use it with heterogeneous forest areas. 
Is there a density or average distance parameters between trees in order to limit over-segmentation or under-segmentation of certain areas.
thank you in advance.
William

**Comment by andrew-plowright** [comment]
Hi William, parameterizing the `vwf` function is somewhere between an art and a science. The algorithm's developers [published a few studies](https://www.ingentaconnect.com/content/asprs/pers/2004/00000070/00000005/art00003) on techniques for setting parameters, so I'd suggest starting there. But for heterogenous forests, I'm afraid I haven't personally found a reliable approach other than to stratify the area of interest into different zones and then apply different parameters for each zone. For instance, I often use this for urban canopy studies, whereby I have discrete "street tree", "parkland" and "forest" zones, each of which has different `vwf` parameters.

Probably not the most helpful answer. If you come up with any interest approaches of your own, let me know!
Andrew
