### ISSUE TITLE
Problem with file size in TreeTopFinder (vwf)

### ISSUE THREAD

**Issue by j-arren** [AndyPL22/ForestTools#5]
Hello,

I am implementing the VWF function to a raster of a canopy height model but when I try to run the code it gives me an error. 

My chm file:
```
class       : RasterLayer 
dimensions  : 16462, 13897, 228772414  (nrow, ncol, ncell)
resolution  : 0.5, 0.5  (x, y)
extent      : 237628.7, 244577.2, 583879.5, 592110.5  (xmin, xmax, ymin, ymax)
coord. ref. : NA 
data source :/Users/name/Desktop/CHM.tif
names       : WK000900 
values      : -5.520692, 21.56335  (min, max)
```
The coordinate reference system is not yet loaded but x,y,z are all in meters.

My chm file size is about 1.8 gigabytes:
`file.size("/Users/name/Desktop/CHM.tif")`
`[1] 1830181466`

My code:
`library(ForestTools)`
`library(raster)`
`lin <- function(x){x * 0.22 + 0.6}`
`chm <- raster("~/Desktop/CHM.tif")`
`ttops <- vwf(CHM = chm, winFun = lin, minHeight = 3, maxWinDiameter = NULL)`

My error:
`Error in .local(x, stat, ...) : cannot use this function for large files`

I have implemented the same function on several other rasters and so far I have not encountered any issues.  A file of around 850 MB works fine. I have also tried changing the linear function but this gives an error as well.

Thanks.
Jarren

**Comment by andrew-plowright** [comment]
Hi Jarren, I'm afraid that this error is being produced from within the
'raster' function, which imposes a file size limit. This isn't something I
can change myself, so you'll have to break the CHM into tiles and process
them separately.

**Comment by j-arren** [comment]
Thank you for the quick reply. That is unfortunate as I am dealing with large files that have already been split up. Other then that your package works great though!

**Comment by webb-e** [comment]
Hi!  I am experiencing the same error, but I do not have a large file. Any ideas?

```
 file.size(".../CHM_cropped.tif")
[1] 25957911

CHM<-raster(".../CHM_cropped.tif")
lin <- function(x){x * 0.05 + 0.6} #trying the example function and will go from there
ttops <- vwf(CHM = CHM, winFun = lin, minHeight =2)
```
Error in .local(x, stat, ...) : cannot use this function for large files

**Comment by webb-e** [comment]
Nevermind.  This seems to be solved by the vwf patch.  Thank you.

**Comment by andrew-plowright** [comment]
Glad that worked!

**Comment by kevin-welch** [comment]
I am experiencing the same problem with file size limitations and my .tif is only 39 MB. What is this vwf patch that is referenced above?  Thanks for any insight.

**Comment by webb-e** [comment]
@kevin-welch  https://github.com/andrew-plowright/ForestTools/blob/master/R/vwf.R

**Comment by andrew-plowright** [comment]
@kevin-welch try installing the package from Github

```
 install_github("andrew-plowright/ForestTools")
```
