### ISSUE TITLE
vwf Error

### ISSUE THREAD

**Issue by NatKatUP** [AndyPL22/ForestTools#7]
Hi, 
the vwf function gives me the error: "Error in .local(x, ...) : w must have uneven sides"
lin <- function(x){x * 0.2 + 0.8}
ttops <- vwf(CHM = schm, winFun = lin, minHeight = 2)

Strangely, it works using a slightly shallower winFun <- function(x){x * 0.1 + 0.8}
When I then change  minHeight to 2 the error occurs again. I don't get at all what this error even means but it seems like the steeper the linear function is, the lower I need to set my minHeight!?

**Comment by andrew-plowright** [comment]
Hi, problems are usually partly due to the CHM that is being used. Do you
have a section of a CHM you can send me so I can try and re-create the
error?

**Comment by NatKatUP** [comment]
Here is a data example.
[example_chm_aggregated_smoothed.zip](https://github.com/AndyPL22/ForestTools/files/2772304/example_chm_aggregated_smoothed.zip)

**Comment by andrew-plowright** [comment]
Hi Nat, I wasn't able to re-create this error. Could you install
ForestTools from Github https://github.com/AndyPL22/ForestTools and give it
a try?

**Comment by NatKatUP** [comment]
Thanks, the problem is solved. And thanks for the great package by the way!

**Comment by andrew-plowright** [comment]
Thanks! Glad you've found it to be useful.
