### ISSUE TITLE
Problem with file in TreeTopFinder (vwf)

### ISSUE THREAD

**Issue by dpessi** [AndyPL22/ForestTools#8]
Hello,

I am implementing the VWF function to a raster of a canopy height model but when I try to run the code it gives me an error.

My chm file:

>     class : RasterLayer
>     dimensions : 3944, 3563, 14052472 (nrow, ncol, ncell)
>     resolution : 0.0502, 0.052 (x, y)
>     extent : 758223.1, 758402, 8178203, 8178408 (xmin, xmax, ymin, ymax)
>     coord. ref. : +proj=utm +zone=21 +south +ellps=GRS80 +units=m +no_defs
>     data source : in memory
>     names : área
>     values : -0.856781, 14.27667 (min, max)

My chm file size is about 53.276 kb:

>     file.size("/Users/name/Desktop/CHM.tif")
>     [1] 54553763`

My code:

>     library(ForestTools)
>     library(raster)
>     library(installr)
>     require(rgdal)
>     data=raster("área.TIF")
>     plot(data, xlab = "", ylab = "", xaxt='n', yaxt = 'n')
>     lin <- function(x){x * 0.05 + 0.6}
>     wgs84.p4s <- "+proj=utm +zone=21 +south +ellps=GRS80 +units=m +no_defs"
>     data <- projectRaster(data, crs=wgs84.p4s,method="ngb")
>     plot(data, axes=T)
>     data
>     ttops <- vwf(CHM = data, winFun = lin, minHeight = 0.20)

My error:

>     Error in vwf(CHM = data, winFun = lin, minHeight = 0.2, maxWinDiameter = NULL) :
>     Input 'CHM' does not have square cells

Example with data from ForestTools package:

>     library(ForestTools)
>     library(raster)
>     data("kootenayCHM")
>     par(mar = rep(0.5, 4))
>     plot(kootenayCHM, xlab = "", ylab = "", xaxt='n', yaxt = 'n')
>     lin <- function(x){x * 0.05 + 0.6}
>     ttops <- vwf(CHM = kootenayCHM, winFun = lin, minHeight = 2)
>     plot(kootenayCHM, xlab = "", ylab = "", xaxt='n', yaxt = 'n')
>     plot(ttops, col = "blue", pch = 20, cex = 0.5, add = TRUE)

Thanks.
Dhonatan Pessi

**Comment by andrew-plowright** [comment]
Hi Dhonatan, as the error message says, the function requires square cells to operate accurately. The reason for this is that the `raster::focalWeight()` function is used to generate a circular search window, and if the cell sides are not square, then the window will be oval and the radius determined by the `winFun` argument will not be consistent.

I would also note that the CHM you are using is very high resolution. Depending on your processing power, it make take a long time to run the function. You might want to consider resampling to 0.25 x 0.25 m.

**Comment by dpessi** [comment]
Andrew, thank you for your answer. So, this tool has a height limitation? My data is considered as high values from 0 m until 15 m. It's possible to applied this function on my datas?

**Comment by andrew-plowright** [comment]
It's not that it has a height limitation, but if the search window is very large in terms of pixels then it will require a lot of processing time. Take a window with a 5 m radius, for instance. On a 1 m resolution CHM, the window will be 11 x 11 pixels in size. On a 0.05 m resolution CHM, the window will be 201 x 201 pixels. So that's the real limitation. Does that make sense?

**Comment by dpessi** [comment]
I understood. But I work with datas from UAV (unmanned aerial vehicle), the resolution is very small (about 0.05m). Is possible to apply this tools on identification of trees and measure the canopy with AUV datas that have very small resolution like 0.05m? I tried to generate this process with a speccific cutting in the same data, and the process worked. If you need I post the script and the datas used. 

I have a question about the possibilities of package ForestTools: Is it possible to measure the AGB ( above-ground biomass) as of CHM datas in this package? Do you have any script about that?

Thank you so much, Andrew.

Dhonatan Pessi

**Comment by andrew-plowright** [comment]
I actually use this for UAV data too. It is not necessary to have such a high resolution CHM for identifying individual trees. As long as the CHM resolution is fine enough to not agglomerate distinct stems, then that's all you need. A sub-meter resolution should be good enough. It is certainly possible to apply the function to a CHM at any resolution, but as I mentioned, you may find the function to be quite slow if the resolution is very high.

The `vwf` function will only provide you with the locations of dominant tree stems. The CHM also contains their heights. If you have information about the tree species in the area being surveyed, it may be possible to use allometric equations to estimate AGB, but it won't produce those measurements directly.

**Comment by dpessi** [comment]
Very well. These information helped me a lot. Thank you.

I saw your post intitled "Canopy analysis in R using Forest Tools" link: https://cran.r-project.org/web/packages/ForestTools/vignettes/treetopAnalysis.html. When you use the "sp_summarise", the line "crownAreaMean" would be the area mean canopy of all polygon calculed?

I have a last question: Do you have any example in R that I can to estimate AGB from CHM datas? I searched for all internet parts something about to calculate the agb from CHM datas, but unsuccessfully.

**Comment by andrew-plowright** [comment]
Yes, if you mean the mean area of the individual crown polygons.

I'm afraid I don't, since AGB isn't something I've modeled in the past. If you figure something out, though, I'd be curious to see it. Good luck!
